
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ThreadState extends javax.swing.JPanel
{

    /**
     * Creates new form ThreadState
     */
    public ThreadState()
    {
        initComponents();
        
    }
    
    public void setWaiting()
    {
        lbName.setBackground(Color.orange);
    }
    
    public void setRunning()
    {
        lbName.setBackground(Color.green);
    }
    
    public void setName(String name)
    {
        lbName.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbName = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbName.setText("jLabel1");
        lbName.setOpaque(true);
        add(lbName, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables
}
